enum ErrorsEnum {
  IMAGE_WAS_NOT_PROVIDED = "IMAGE_WAS_NOT_PROVIDED",
  IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND",
  TASK_ID_WAS_NOT_PROVIDED = "TASK_ID_WAS_NOT_PROVIDED",
  THIS_FILE_IS_NOT_AN_IMAGE = "THIS_FILE_IS_NOT_AN_IMAGE",
}

export { ErrorsEnum };
